SELECT col# "2Column Number", NAME, TYPE# 
FROM COL$
WHERE col# = 1;

SELECT OBJ#, COL# AS SEGCOL#
FROM COL$;

SELECT NAME, COUNT(*) AS "NUMBER OF TIMES"
FROM COL$
WHERE COL# = 1
GROUP BY NAME
HAVING COUNT(*)>70
ORDER BY "NUMBER OF TIMES" ASC, NAME DESC;

SELECT NAME
FROM COL$
WHERE COL# = 1 AND COUNT(*)>5;

SELECT NAME
FROM COL$
WHERE COL# = 1
GROUP BY NAME;

SELECT COL# AS "COLUMN NUMBER"
FROM COL$
GROUP BY COL#;